/* eslint-disable no-undef */
const images = {
  logo: require('../static/images/logo.png'),
  background: require('../static/images/background.jpeg'),
  logoCircle: require('../static/images/logoCircle.png'),
  icMenu: require('../static/images/Icons/menu.svg'),
  icCloseMenu: require('../static/images/Icons/close-menu.svg'),
  icUpload: require('../static/images/Icons/upload.svg'),
  icRemoveImage: require('../static/images/Icons/remove-image.svg'),
  icEmail: require('../static/images/Icons/email.svg'),
  icTelegram: require('../static/images/Icons/telegram.svg'),
  icTwitter: require('../static/images/Icons/twitter.svg'),
  icClose: require('../static/images/Icons/close.svg'),
  icCopy: require('../static/images/Icons/copy.svg'),
  icSelect: require('../static/images/Icons/icSelect.svg'),
  icDropdown: require('../static/images/Icons/icDropdown.svg'),
  icKeyring: require('../static/images/Icons/keyring.svg'),
  icCheck: require('../static/images/Icons/check.svg'),
  icCheckActive: require('../static/images/Icons/checkActive.svg'),
  icSwap: require('../static/images/Icons/swap.svg'),
  icStatusSuccess: '/../static/images/Icons/success-status-ic.svg',
  icStatusPending: '/../static/images/Icons/pending-status-ic.svg',
  icStatusFailed: '/../static/images/Icons/failed-status-ic.svg',
  icEmail2: '/../static/images/Icons/footer-email.svg',
  ictwiter: '/../static/images/Icons/footer-twiter.svg',
  logoFooter: '/../static/images/Icons/ic-footer.svg',
  icDropUp: '/../static/images/Icons/icDropUp.svg',
  icHelpful: require('../static/images/Icons/helpful.svg'),
  icHelpfulActive: require('../static/images/Icons/helpfulActive.svg'),
  icMessage: require('../static/images/Icons/icMessage.svg'),
  icLeftArrow: require('../static/images/Icons/left-arrow.svg'),
  flags: {
    en: require('../static/images/Icons/Flags/en.svg'),
    ja: require('../static/images/Icons/Flags/ja.svg'),
    cn: require('../static/images/Icons/Flags/cn.svg'),
  },
}

export default images
